// Overlay file for a project scaffolded with `npm create @microsoft/rayfin@latest`.
// Pattern from https://rayfin.ai/docs/connectors/kusto and https://rayfin.ai/docs/functions/calling-functions
//
// Prerequisites (run in the project root):
//   npx rayfin connector add --type kusto --workspace-id <workspace-id> --item-id <kql-database-item-id> --name rail
//   (then run the pinned `npm install ...` command the CLI prints)
//   npx rayfin functions init        # EXPERIMENTAL - only if functions are available in your tenant/region
//
// rayfin/connectors/rail/schema.ts is GENERATED by the CLI - do not hand-edit it.
// The connector key `rail` must match in rayfin.yml, AppConnectorsSchema, `connectors` and the runtime map.
//
// ASSUMPTION (verify against the SDK reference for your version): the second type parameter of
// ConnectorsRayfinClient is the functions schema (the docs example passes Record<string, never> there).
import { ConnectorsRayfinClient } from '@microsoft/rayfin-client/experimental';
import { kusto } from '@microsoft/rayfin-connector-kusto';
import type { AppSchema } from '../../rayfin/data/schema';
import type { AppFunctionsSchema } from '../../rayfin/functions/src/types.js';
import type { RailSchema } from '../../rayfin/connectors/rail/schema';
import { connectorConfig as railConfig } from '../../rayfin/connectors/rail/schema';

type AppConnectorsSchema = {
  rail: RailSchema;
};

export const client = new ConnectorsRayfinClient<AppSchema, AppFunctionsSchema, AppConnectorsSchema>(
  {
    baseUrl: import.meta.env.VITE_RAYFIN_API_URL,
    publishableKey: import.meta.env.VITE_RAYFIN_PUBLISHABLE_KEY,
    connectors: {
      rail: railConfig,
    },
  },
  {
    rail: kusto(),
  },
);
